blank_issues_enabled: true
contact_links:
  - name: MIT App Inventor Community
    url: https://community.appinventor.mit.edu/c/mit-app-inventor-help/5
    about: Looking for help while developing your apps? Ask in the Community your doubts and questions!
